---
- name: Deploy React App to EC2 Target via NGINX
  hosts: react-target
  become: yes
  vars:
    app_name: my-quizzt
    dest_dir: /var/www/my-quizzt

  tasks:
    - name: Install NGINX
      yum:
        name: nginx
        state: present

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: true

    - name: Ensure destination directory exists
      file:
        path: "{{ dest_dir }}"
        state: directory
        owner: nginx
        group: nginx
        mode: '0755'

    - name: Upload React build artifact
      unarchive:
        src: /var/lib/jenkins/workspace/Test/build_artifacts.tar.gz
        dest: "{{ dest_dir }}"
        remote_src: no
        extra_opts: [--strip-components=2]
      tags: unpack

    - name: Copy NGINX configuration
      template:
        src: react_nginx.conf.j2
        dest: /etc/nginx/conf.d/{{ app_name }}.conf

    - name: Remove default NGINX config (if exists)
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Reload NGINX to apply changes
      service:
        name: nginx
        state: reloaded
